model:
    name: qwen_image
    pretrained_model_name_or_path: /data/nvme1/models/Qwen/Qwen-Image-2512
    max_sequence_length: 1024
    running_dtype: bf16

data:
    train:
        name: image_dataset
        num_workers: 8
        prompt_dropout_rate: 0.1
        target_area: 1048576 # 1024 * 1024
        shuffle: true
        # examples: https://github.com/ModelTC/LightX2V_train_data_examples
        data_path:
            - /data/nvme1/yongyang/kkk/LightX2V_train_data_examples/dataset_v1/train.jsonl
    val:
        name: image_dataset
        num_workers: 8
        shuffle: false
        data_path:
            - /data/nvme1/yongyang/kkk/LightX2V_train_data_examples/dataset_v1/val.jsonl

scheduler:
    num_train_timesteps: 1000
    timestep_distribution: logitnormal
    logitnormal_mean: 0.0
    logitnormal_std: 1.0
    min_t: 0.001
    max_t: 1.0
    time_shift_settings:
        do_time_shift: true
        shift_type: exponential
        # shift function: "linear" => mu/(mu+(1/t-1)^p), "exponential" => exp(mu)/(exp(mu)+(1/t-1)^p)
        time_shift_power: 1.0
        dynamic_shift: true
        patch_size: [2, 2]  # [H, W]
        # https://github.com/huggingface/diffusers/blob/v0.38.0/src/diffusers/pipelines/qwenimage/pipeline_qwenimage.py#L59
        shift_x1: 256
        shift_x2: 4096
        shift_y1: 0.5
        shift_y2: 1.15

training:
    method: lora
    max_train_iters: 3000
    gradient_accumulation_iters: 1
    gradient_checkpointing: true
    max_grad_norm: 1.0
    lr_scheduler: constant
    lr_warmup_iters: 10
    save_every_iters: 100
    save_total_limit: 10
    lora:
        rank: 16
        alpha: 16
        target_modules:
            - to_k
            - to_q
            - to_v
            - to_out.0
    optimizer:
        learning_rate: 0.0001
        adam_beta1: 0.9
        adam_beta2: 0.999
        weight_decay: 0.01
        adam_epsilon: 0.00000001
    output_dir: ./output_train/qwen_image_lora

inference:
    method: image_infer
    negative_prompt: " "
    default_width: 1024
    default_height: 1024
    num_inference_steps: 50
    enable_cfg: true
    cfg_guidance_scale: 4.0
    seed: 42
    output_dir: ./output_infer/qwen_image_lora
    infer_every_iters: ${training.save_every_iters}

resume:
    auto_resume: true
